"""Unit tests for the per-asset CLIs.

These exercise the CLI layer in isolation: argument parsing, verb-to-method
routing (including the sub-resource commands generated by the shared harness),
and JSON output. The underlying resource clients are stubbed with spies — their
HTTP behaviour is covered by the resource unit tests. Building an
``ExoscaleClient`` from dummy env credentials performs no network I/O, so the
spies fully isolate the CLI.
"""

from __future__ import annotations

import json
from typing import Any, List

import pytest

from exoscale_connector.cli._base import run_resource_cli
from exoscale_connector.cli.dbaas import main as dbaas_main
from exoscale_connector.cli.dns import main as dns_main
from exoscale_connector.cli.sks import main as sks_main
from exoscale_connector.resources.dbaas import DBaaSServiceClient
from exoscale_connector.resources.dns import DnsDomainClient
from exoscale_connector.resources.security_group import SecurityGroupClient
from exoscale_connector.resources.sks import SksClusterClient


@pytest.fixture(autouse=True)
def cli_env(monkeypatch) -> None:
    """Dummy credentials so ExoscaleClient.from_env() succeeds (no network)."""
    monkeypatch.setenv("EXOSCALE_API_KEY", "EXOtestkey")
    monkeypatch.setenv("EXOSCALE_API_SECRET", "testsecret")
    monkeypatch.setenv("EXOSCALE_ZONE", "de-fra-1")


def _spy(ret: Any):
    """A class-method replacement that records (args, kwargs) and returns ret."""

    def fn(self, *args, **kwargs):
        fn.calls.append((args, kwargs))
        return ret

    fn.calls = []  # type: ignore[attr-defined]
    return fn


def _stub(monkeypatch, cls, method: str, ret: Any):
    fn = _spy(ret)
    monkeypatch.setattr(cls, method, fn)
    return fn


def _out(capsys) -> Any:
    return json.loads(capsys.readouterr().out)


# ------------------------------------------------------------------ #
# dns — primary (domain) + sub-resource (record)
# ------------------------------------------------------------------ #


def test_dns_list_domains(monkeypatch, capsys) -> None:
    spy = _stub(monkeypatch, DnsDomainClient, "list", [{"id": "d1"}])
    assert dns_main(["list-domains"]) == 0
    assert spy.calls == [((), {})]
    assert _out(capsys) == [{"id": "d1"}]


def test_dns_get_domain(monkeypatch, capsys) -> None:
    spy = _stub(monkeypatch, DnsDomainClient, "get", {"id": "d1"})
    assert dns_main(["get-domain", "--id", "d1"]) == 0
    assert spy.calls == [(("d1",), {})]


def test_dns_create_domain_no_wait(monkeypatch, capsys) -> None:
    spy = _stub(monkeypatch, DnsDomainClient, "create", {"id": "d-new"})
    assert dns_main(["create-domain", "--json", '{"unicode-name": "ex.com"}', "--no-wait"]) == 0
    assert spy.calls == [(({"unicode-name": "ex.com"},), {"wait": False})]


def test_dns_list_records(monkeypatch, capsys) -> None:
    spy = _stub(monkeypatch, DnsDomainClient, "list_records", [{"id": "r1"}])
    assert dns_main(["list-records", "--domain-id", "d1"]) == 0
    assert spy.calls == [(("d1",), {})]
    assert _out(capsys) == [{"id": "r1"}]


def test_dns_create_record(monkeypatch, capsys) -> None:
    spy = _stub(monkeypatch, DnsDomainClient, "create_record", {"id": "r-new"})
    rc = dns_main(["create-record", "--domain-id", "d1", "--json", '{"type": "TXT"}'])
    assert rc == 0
    assert spy.calls == [(("d1", {"type": "TXT"}), {"wait": True})]


def test_dns_delete_record(monkeypatch, capsys) -> None:
    spy = _stub(monkeypatch, DnsDomainClient, "delete_record", {"state": "success"})
    assert dns_main(["delete-record", "--domain-id", "d1", "--id", "r1"]) == 0
    assert spy.calls == [(("d1", "r1"), {"wait": True})]


# ------------------------------------------------------------------ #
# sks — primary (cluster) + sub-resource (nodepool)
# ------------------------------------------------------------------ #


def test_sks_list_clusters(monkeypatch, capsys) -> None:
    spy = _stub(monkeypatch, SksClusterClient, "list", [{"id": "c1"}])
    assert sks_main(["list-clusters"]) == 0
    assert spy.calls == [((), {})]


def test_sks_list_nodepools(monkeypatch, capsys) -> None:
    spy = _stub(monkeypatch, SksClusterClient, "list_nodepools", [{"id": "np1"}])
    assert sks_main(["list-nodepools", "--cluster-id", "c1"]) == 0
    assert spy.calls == [(("c1",), {})]


def test_sks_create_nodepool(monkeypatch, capsys) -> None:
    spy = _stub(monkeypatch, SksClusterClient, "create_nodepool", {"id": "np-new"})
    rc = sks_main(["create-nodepool", "--cluster-id", "c1", "--json", '{"name": "pool"}'])
    assert rc == 0
    assert spy.calls == [(("c1", {"name": "pool"}), {"wait": True})]


def test_sks_delete_nodepool(monkeypatch, capsys) -> None:
    spy = _stub(monkeypatch, SksClusterClient, "delete_nodepool", {"state": "success"})
    assert sks_main(["delete-nodepool", "--cluster-id", "c1", "--id", "np1"]) == 0
    assert spy.calls == [(("c1", "np1"), {"wait": True})]


# ------------------------------------------------------------------ #
# dbaas — bespoke name-keyed verbs
# ------------------------------------------------------------------ #


def test_dbaas_list(monkeypatch, capsys) -> None:
    spy = _stub(monkeypatch, DBaaSServiceClient, "list", [{"name": "pg-1"}])
    assert dbaas_main(["list"]) == 0
    assert spy.calls == [((), {})]


def test_dbaas_get_by_name(monkeypatch, capsys) -> None:
    spy = _stub(monkeypatch, DBaaSServiceClient, "get", {"name": "pg-1"})
    assert dbaas_main(["get", "--name", "pg-1"]) == 0
    assert spy.calls == [(("pg-1",), {})]


def test_dbaas_create_type_specific(monkeypatch, capsys) -> None:
    spy = _stub(monkeypatch, DBaaSServiceClient, "create", {"name": "pg-1"})
    rc = dbaas_main(
        ["create", "--type", "pg", "--name", "pg-1", "--json", '{"plan": "hobbyist-2"}']
    )
    assert rc == 0
    assert spy.calls == [(({"plan": "hobbyist-2"},), {"service_type": "pg", "name": "pg-1"})]


def test_dbaas_create_without_body(monkeypatch, capsys) -> None:
    spy = _stub(monkeypatch, DBaaSServiceClient, "create", {"name": "pg-1"})
    assert dbaas_main(["create", "--type", "pg", "--name", "pg-1"]) == 0
    assert spy.calls == [(({},), {"service_type": "pg", "name": "pg-1"})]


def test_dbaas_delete_by_name(monkeypatch, capsys) -> None:
    spy = _stub(monkeypatch, DBaaSServiceClient, "delete", {"state": "success"})
    assert dbaas_main(["delete", "--name", "pg-1"]) == 0
    assert spy.calls == [(("pg-1",), {})]


# ------------------------------------------------------------------ #
# Regression: the bare-verb path (15 single-resource CLIs) is unchanged
# ------------------------------------------------------------------ #


def _sg_cli(argv: List[str]) -> int:
    return run_resource_cli(
        SecurityGroupClient,
        prog="exoscale-security-group",
        description="Manage Exoscale security groups via the APIv2.",
        argv=argv,
    )


def test_bare_harness_list_still_works(monkeypatch, capsys) -> None:
    spy = _stub(monkeypatch, SecurityGroupClient, "list", [{"id": "sg1"}])
    assert _sg_cli(["list"]) == 0
    assert spy.calls == [((), {})]
    assert _out(capsys) == [{"id": "sg1"}]


def test_bare_harness_create_no_wait(monkeypatch, capsys) -> None:
    spy = _stub(monkeypatch, SecurityGroupClient, "create", {"id": "sg-new"})
    assert _sg_cli(["create", "--json", '{"name": "web"}', "--no-wait"]) == 0
    assert spy.calls == [(({"name": "web"},), {"wait": False})]


def test_no_command_prints_help_exit_2(capsys) -> None:
    assert dns_main([]) == 2
    assert sks_main([]) == 2
    assert dbaas_main([]) == 2
