"""Unit tests for the per-asset CLIs.

These exercise the CLI layer in isolation: argument parsing, verb-to-method
routing (including the sub-resource commands generated by the shared harness),
and JSON output. The underlying resource clients are stubbed with spies — their
HTTP behaviour is covered by the resource unit tests. Building an
``ExoscaleClient`` from dummy env credentials performs no network I/O, so the
spies fully isolate the CLI.
"""

from __future__ import annotations

import importlib
import io
import json
import sys
from typing import Any

import pytest
import requests

from exoscale_connector.cli._base import run_resource_cli
from exoscale_connector.cli.dbaas import main as dbaas_main
from exoscale_connector.cli.dns import main as dns_main
from exoscale_connector.cli.event import main as event_main
from exoscale_connector.cli.kms import main as kms_main
from exoscale_connector.cli.sks import main as sks_main
from exoscale_connector.cli.template import main as template_main
from exoscale_connector.cli.vpc import main as vpc_main
from exoscale_connector.errors import APIError
from exoscale_connector.resources.block_volume_snapshot import BlockVolumeSnapshotClient
from exoscale_connector.resources.dbaas import DBaaSServiceClient
from exoscale_connector.resources.dns import DnsDomainClient
from exoscale_connector.resources.event import EventClient
from exoscale_connector.resources.kms import KmsKeyClient
from exoscale_connector.resources.security_group import SecurityGroupClient
from exoscale_connector.resources.sks import SksClusterClient
from exoscale_connector.resources.snapshot import SnapshotClient
from exoscale_connector.resources.template import TemplateClient
from exoscale_connector.resources.vpc import VpcClient


@pytest.fixture(autouse=True)
def cli_env(monkeypatch) -> None:
    """Dummy credentials so ExoscaleClient.from_env() succeeds (no network)."""
    monkeypatch.setenv("EXOSCALE_API_KEY", "EXOtestkey")
    monkeypatch.setenv("EXOSCALE_API_SECRET", "testsecret")
    monkeypatch.setenv("EXOSCALE_ZONE", "de-fra-1")


def _spy(ret: Any):
    """A class-method replacement that records (args, kwargs) and returns ret."""

    def fn(self, *args, **kwargs):
        fn.calls.append((args, kwargs))
        return ret

    fn.calls = []  # type: ignore[attr-defined]
    return fn


def _stub(monkeypatch, cls, method: str, ret: Any):
    fn = _spy(ret)
    monkeypatch.setattr(cls, method, fn)
    return fn


def _out(capsys) -> Any:
    return json.loads(capsys.readouterr().out)


# ------------------------------------------------------------------ #
# dns — primary (domain) + sub-resource (record)
# ------------------------------------------------------------------ #


def test_dns_list_domains(monkeypatch, capsys) -> None:
    spy = _stub(monkeypatch, DnsDomainClient, "list", [{"id": "d1"}])
    assert dns_main(["list-domains"]) == 0
    assert spy.calls == [((), {})]
    assert _out(capsys) == [{"id": "d1"}]


def test_dns_get_domain(monkeypatch, capsys) -> None:
    spy = _stub(monkeypatch, DnsDomainClient, "get", {"id": "d1"})
    assert dns_main(["get-domain", "--id", "d1"]) == 0
    assert spy.calls == [(("d1",), {})]


def test_dns_create_domain_no_wait(monkeypatch, capsys) -> None:
    spy = _stub(monkeypatch, DnsDomainClient, "create", {"id": "d-new"})
    assert dns_main(["create-domain", "--json", '{"unicode-name": "ex.com"}', "--no-wait"]) == 0
    assert spy.calls == [(({"unicode-name": "ex.com"},), {"wait": False})]


def test_dns_list_records(monkeypatch, capsys) -> None:
    spy = _stub(monkeypatch, DnsDomainClient, "list_records", [{"id": "r1"}])
    assert dns_main(["list-records", "--domain-id", "d1"]) == 0
    assert spy.calls == [(("d1",), {})]
    assert _out(capsys) == [{"id": "r1"}]


def test_dns_create_record(monkeypatch, capsys) -> None:
    spy = _stub(monkeypatch, DnsDomainClient, "create_record", {"id": "r-new"})
    rc = dns_main(["create-record", "--domain-id", "d1", "--json", '{"type": "TXT"}'])
    assert rc == 0
    assert spy.calls == [(("d1", {"type": "TXT"}), {"wait": True})]


def test_dns_delete_record(monkeypatch, capsys) -> None:
    spy = _stub(monkeypatch, DnsDomainClient, "delete_record", {"state": "success"})
    assert dns_main(["delete-record", "--domain-id", "d1", "--id", "r1"]) == 0
    assert spy.calls == [(("d1", "r1"), {"wait": True})]


# ------------------------------------------------------------------ #
# sks — primary (cluster) + sub-resource (nodepool)
# ------------------------------------------------------------------ #


def test_sks_list_clusters(monkeypatch, capsys) -> None:
    spy = _stub(monkeypatch, SksClusterClient, "list", [{"id": "c1"}])
    assert sks_main(["list-clusters"]) == 0
    assert spy.calls == [((), {})]


def test_sks_list_nodepools(monkeypatch, capsys) -> None:
    spy = _stub(monkeypatch, SksClusterClient, "list_nodepools", [{"id": "np1"}])
    assert sks_main(["list-nodepools", "--cluster-id", "c1"]) == 0
    assert spy.calls == [(("c1",), {})]


def test_sks_create_nodepool(monkeypatch, capsys) -> None:
    spy = _stub(monkeypatch, SksClusterClient, "create_nodepool", {"id": "np-new"})
    rc = sks_main(["create-nodepool", "--cluster-id", "c1", "--json", '{"name": "pool"}'])
    assert rc == 0
    assert spy.calls == [(("c1", {"name": "pool"}), {"wait": True})]


def test_sks_delete_nodepool(monkeypatch, capsys) -> None:
    spy = _stub(monkeypatch, SksClusterClient, "delete_nodepool", {"state": "success"})
    assert sks_main(["delete-nodepool", "--cluster-id", "c1", "--id", "np1"]) == 0
    assert spy.calls == [(("c1", "np1"), {"wait": True})]


# ------------------------------------------------------------------ #
# dbaas — bespoke name-keyed verbs
# ------------------------------------------------------------------ #


def test_dbaas_list(monkeypatch, capsys) -> None:
    spy = _stub(monkeypatch, DBaaSServiceClient, "list", [{"name": "pg-1"}])
    assert dbaas_main(["list"]) == 0
    assert spy.calls == [((), {})]


def test_dbaas_get_by_name(monkeypatch, capsys) -> None:
    spy = _stub(monkeypatch, DBaaSServiceClient, "get", {"name": "pg-1"})
    assert dbaas_main(["get", "--name", "pg-1"]) == 0
    assert spy.calls == [(("pg-1",), {})]


def test_dbaas_create_type_specific(monkeypatch, capsys) -> None:
    spy = _stub(monkeypatch, DBaaSServiceClient, "create", {"name": "pg-1"})
    rc = dbaas_main(
        ["create", "--type", "pg", "--name", "pg-1", "--json", '{"plan": "hobbyist-2"}']
    )
    assert rc == 0
    assert spy.calls == [(({"plan": "hobbyist-2"},), {"service_type": "pg", "name": "pg-1"})]


def test_dbaas_create_without_body(monkeypatch, capsys) -> None:
    spy = _stub(monkeypatch, DBaaSServiceClient, "create", {"name": "pg-1"})
    assert dbaas_main(["create", "--type", "pg", "--name", "pg-1"]) == 0
    assert spy.calls == [(({},), {"service_type": "pg", "name": "pg-1"})]


def test_dbaas_delete_by_name(monkeypatch, capsys) -> None:
    spy = _stub(monkeypatch, DBaaSServiceClient, "delete", {"state": "success"})
    assert dbaas_main(["delete", "--name", "pg-1"]) == 0
    assert spy.calls == [(("pg-1",), {})]


# ------------------------------------------------------------------ #
# Regression: the bare-verb path (15 single-resource CLIs) is unchanged
# ------------------------------------------------------------------ #


def _sg_cli(argv: list[str]) -> int:
    return run_resource_cli(
        SecurityGroupClient,
        prog="exoscale-security-group",
        description="Manage Exoscale security groups via the APIv2.",
        argv=argv,
    )


def test_bare_harness_list_still_works(monkeypatch, capsys) -> None:
    spy = _stub(monkeypatch, SecurityGroupClient, "list", [{"id": "sg1"}])
    assert _sg_cli(["list"]) == 0
    assert spy.calls == [((), {})]
    assert _out(capsys) == [{"id": "sg1"}]


def test_bare_harness_create_no_wait(monkeypatch, capsys) -> None:
    spy = _stub(monkeypatch, SecurityGroupClient, "create", {"id": "sg-new"})
    assert _sg_cli(["create", "--json", '{"name": "web"}', "--no-wait"]) == 0
    assert spy.calls == [(({"name": "web"},), {"wait": False})]


def test_no_command_prints_help_exit_2(capsys) -> None:
    assert dns_main([]) == 2
    assert sks_main([]) == 2
    assert dbaas_main([]) == 2


# ------------------------------------------------------------------ #
# Error contract: an "error:" line on stderr and an exit code, no traceback
# ------------------------------------------------------------------ #


def _raise(exc: BaseException):
    def fn(self, *args, **kwargs):
        raise exc

    return fn


@pytest.mark.parametrize(
    "exc,code,message",
    [
        (APIError("boom", status_code=500), 1, "error: boom"),
        (requests.exceptions.ConnectionError("connection dropped"), 1, "error: request failed"),
        (KeyboardInterrupt(), 130, "error: interrupted"),
    ],
)
def test_cli_reports_failures_without_traceback(monkeypatch, capsys, exc, code, message) -> None:
    monkeypatch.setattr(SecurityGroupClient, "list", _raise(exc))
    assert _sg_cli(["list"]) == code
    err = capsys.readouterr().err
    assert err.startswith(message)
    assert "Traceback" not in err


def test_cli_reports_missing_payload_file(tmp_path, capsys) -> None:
    missing = tmp_path / "nope.json"
    assert _sg_cli(["create", "--file", str(missing)]) == 1
    err = capsys.readouterr().err
    assert err.startswith("error: cannot read payload file")
    assert "Traceback" not in err


def test_object_storage_cli_reports_request_failure(monkeypatch, capsys) -> None:
    from exoscale_connector.cli import object_storage

    # Stub the client class too: CI runs without the optional boto3 extra.
    monkeypatch.setattr(object_storage, "BucketClient", lambda config, zone=None: object())
    monkeypatch.setattr(
        object_storage, "_dispatch", _raise(requests.exceptions.Timeout("read timed out"))
    )
    assert object_storage.main(["list"]) == 1
    assert capsys.readouterr().err.startswith("error: request failed")


# ------------------------------------------------------------------ #
# dbaas / kms create: optional --json or --file ('-' = stdin)
# ------------------------------------------------------------------ #


def test_dbaas_create_reads_secret_payload_from_stdin(monkeypatch, capsys) -> None:
    # Secrets (admin-password) belong on stdin/--file, not in the process list.
    spy = _stub(monkeypatch, DBaaSServiceClient, "create", {"name": "pg-1"})
    monkeypatch.setattr(sys, "stdin", io.StringIO('{"plan": "hobbyist-2", "admin-password": "x"}'))
    assert dbaas_main(["create", "--type", "pg", "--name", "pg-1", "--file", "-"]) == 0
    assert spy.calls == [
        (({"plan": "hobbyist-2", "admin-password": "x"},), {"service_type": "pg", "name": "pg-1"})
    ]


def test_dbaas_create_still_accepts_inline_json(monkeypatch, capsys) -> None:
    spy = _stub(monkeypatch, DBaaSServiceClient, "create", {"name": "pg-1"})
    assert dbaas_main(["create", "--type", "pg", "--name", "pg-1", "--json", '{"plan": "x"}']) == 0
    assert spy.calls[0][0] == ({"plan": "x"},)


def test_kms_create_without_payload_sends_empty_body(monkeypatch, capsys) -> None:
    spy = _stub(monkeypatch, KmsKeyClient, "create", {"id": "k1"})
    assert kms_main(["create"]) == 0
    assert spy.calls == [(({},), {})]


# ------------------------------------------------------------------ #
# Read-only collections: no phantom create verb
# ------------------------------------------------------------------ #


@pytest.mark.parametrize("module", ["snapshot", "block_volume_snapshot"])
def test_snapshot_clis_expose_no_create_verb(module, capsys) -> None:
    # /snapshot and /block-storage-snapshot have no POST in the spec.
    main = importlib.import_module(f"exoscale_connector.cli.{module}").main
    with pytest.raises(SystemExit) as exc:
        main(["create", "--json", "{}"])
    assert exc.value.code == 2
    assert "invalid choice: 'create'" in capsys.readouterr().err


def test_bare_harness_keeps_create_by_default(capsys) -> None:
    with pytest.raises(SystemExit):
        _sg_cli(["--help"])
    assert "{list,get,find,create,delete}" in capsys.readouterr().out


# ------------------------------------------------------------------ #
# Harness: payload sources, credentials, help, umbrella exit codes
# ------------------------------------------------------------------ #


def test_create_reads_payload_file(monkeypatch, tmp_path) -> None:
    spy = _stub(monkeypatch, SecurityGroupClient, "create", {"id": "sg-new"})
    payload = tmp_path / "sg.json"
    payload.write_text('{"name": "web"}', encoding="utf-8")
    assert _sg_cli(["create", "--file", str(payload), "--no-wait"]) == 0
    assert spy.calls == [(({"name": "web"},), {"wait": False})]


def test_create_reads_payload_from_stdin(monkeypatch) -> None:
    spy = _stub(monkeypatch, SecurityGroupClient, "create", {"id": "sg-new"})
    monkeypatch.setattr(sys, "stdin", io.StringIO('{"name": "web"}'))
    assert _sg_cli(["create", "--file", "-", "--no-wait"]) == 0
    assert spy.calls[0][0] == ({"name": "web"},)


@pytest.mark.parametrize(
    "raw,message", [("not json", "invalid JSON payload"), ("[1]", "must be a JSON object")]
)
def test_create_rejects_bad_payload(raw, message, capsys) -> None:
    assert _sg_cli(["create", "--json", raw]) == 1
    assert message in capsys.readouterr().err


def test_missing_credentials_is_reported(monkeypatch, capsys) -> None:
    monkeypatch.delenv("EXOSCALE_API_KEY")
    assert _sg_cli(["list"]) == 1
    assert "EXOSCALE_API_KEY" in capsys.readouterr().err


def test_find_without_match_prints_null(monkeypatch, capsys) -> None:
    _stub(monkeypatch, SecurityGroupClient, "find_by_name", None)
    assert _sg_cli(["find", "--name", "nope"]) == 0
    assert _out(capsys) is None


def test_no_command_help_goes_to_stderr(capsys) -> None:
    assert _sg_cli([]) == 2
    captured = capsys.readouterr()
    assert "usage:" in captured.err
    assert captured.out == ""


def test_umbrella_propagates_asset_failure(monkeypatch, capsys) -> None:
    from exoscale_connector.cli.main import main as umbrella_main

    monkeypatch.setattr(SecurityGroupClient, "list", _raise(APIError("denied", status_code=403)))
    assert umbrella_main(["security-group", "list"]) == 1


# ------------------------------------------------------------------ #
# kms
# ------------------------------------------------------------------ #


@pytest.mark.parametrize(
    "argv,method,expected",
    [
        (["list"], "list", ((), {})),
        (["get", "--id", "k"], "get", (("k",), {})),
        (["enable", "--id", "k"], "enable", (("k",), {})),
        (["disable", "--id", "k"], "disable", (("k",), {})),
        (["rotate", "--id", "k"], "rotate", (("k",), {})),
        (
            ["enable-rotation", "--id", "k", "--period", "30"],
            "enable_rotation",
            (("k",), {"rotation_period": 30}),
        ),
        (["disable-rotation", "--id", "k"], "disable_rotation", (("k",), {})),
        (["list-rotations", "--id", "k"], "list_rotations", (("k",), {})),
        (
            ["schedule-deletion", "--id", "k", "--delay-days", "7"],
            "schedule_deletion",
            (("k",), {"delay_days": 7}),
        ),
        (["cancel-deletion", "--id", "k"], "cancel_deletion", (("k",), {})),
        (["replicate", "--id", "k", "--to-zone", "at-vie-1"], "replicate", (("k", "at-vie-1"), {})),
        (["create", "--json", '{"name": "app-key"}'], "create", (({"name": "app-key"},), {})),
    ],
)
def test_kms_routes_each_verb(monkeypatch, capsys, argv, method, expected) -> None:
    spy = _stub(monkeypatch, KmsKeyClient, method, {})
    assert kms_main(argv) == 0
    assert spy.calls == [expected]


# ------------------------------------------------------------------ #
# vpc / template / event
# ------------------------------------------------------------------ #


def test_vpc_list_vpcs(monkeypatch, capsys) -> None:
    spy = _stub(monkeypatch, VpcClient, "list", [{"id": "v1"}])
    assert vpc_main(["list-vpcs"]) == 0
    assert spy.calls == [((), {})]
    assert _out(capsys) == [{"id": "v1"}]


def test_vpc_subnet_sub_resource(monkeypatch, capsys) -> None:
    lst = _stub(monkeypatch, VpcClient, "list_subnets", [{"id": "s1"}])
    create = _stub(monkeypatch, VpcClient, "create_subnet", {"id": "op"})
    delete = _stub(monkeypatch, VpcClient, "delete_subnet", {"id": "op"})
    assert vpc_main(["list-subnets", "--vpc-id", "v1"]) == 0
    assert vpc_main(["create-subnet", "--vpc-id", "v1", "--json", '{"name": "app"}']) == 0
    assert vpc_main(["delete-subnet", "--vpc-id", "v1", "--id", "s1", "--no-wait"]) == 0
    assert lst.calls == [(("v1",), {})]
    assert create.calls == [(("v1", {"name": "app"}), {"wait": True})]
    assert delete.calls == [(("v1", "s1"), {"wait": False})]


def test_template_find_and_create(monkeypatch, capsys) -> None:
    find = _stub(monkeypatch, TemplateClient, "find_by_name", {"id": "t1"})
    create = _stub(monkeypatch, TemplateClient, "create", {"id": "t2"})
    assert template_main(["find-template", "--name", "Linux Debian 12"]) == 0
    assert template_main(["create-template", "--json", '{"name": "img"}', "--no-wait"]) == 0
    assert find.calls == [(("Linux Debian 12",), {})]
    assert create.calls == [(({"name": "img"},), {"wait": False})]


def test_event_list(monkeypatch, capsys) -> None:
    spy = _stub(monkeypatch, EventClient, "list", [{"id": "e1"}])
    assert event_main(["list-events"]) == 0
    assert spy.calls == [((), {})]


@pytest.mark.parametrize(
    "module,cls",
    [("snapshot", SnapshotClient), ("block_volume_snapshot", BlockVolumeSnapshotClient)],
)
def test_snapshot_clis_list_and_delete(monkeypatch, capsys, module, cls) -> None:
    main = importlib.import_module(f"exoscale_connector.cli.{module}").main
    lst = _stub(monkeypatch, cls, "list", [{"id": "s1"}])
    delete = _stub(monkeypatch, cls, "delete", {"state": "success"})
    assert main(["list"]) == 0
    assert main(["delete", "--id", "s1", "--no-wait"]) == 0
    assert lst.calls == [((), {})]
    assert delete.calls == [(("s1",), {"wait": False})]


# ------------------------------------------------------------------ #
# object storage (bespoke dispatch over BucketClient)
# ------------------------------------------------------------------ #


def test_object_storage_routes_bucket_and_object_verbs(monkeypatch, capsys) -> None:
    pytest.importorskip("boto3")
    from exoscale_connector.cli.object_storage import main as sos_main
    from exoscale_connector.resources.object_storage import BucketClient

    create = _stub(monkeypatch, BucketClient, "create", None)
    lst = _stub(monkeypatch, BucketClient, "list_objects", [])
    sign = _stub(monkeypatch, BucketClient, "presign_put", "https://signed")
    assert sos_main(["create", "--name", "b1"]) == 0
    assert sos_main(["list-objects", "--bucket", "b1", "--prefix", "logs/"]) == 0
    assert sos_main(["presign", "--bucket", "b1", "--key", "k", "--method", "put"]) == 0
    assert create.calls == [(("b1",), {})]
    assert lst.calls == [(("b1",), {"prefix": "logs/", "limit": None})]
    assert sign.calls == [(("b1", "k"), {"expires_in": 3600})]
